chore: prepare for llrfctrl executable name change

diff --git a/doocs-llrfctrl-server/postinst b/doocs-llrfctrl-server/postinst
--- a/doocs-llrfctrl-server/postinst
+++ b/doocs-llrfctrl-server/postinst
@@ -16,9 +16,16 @@ case "$1" in
 	;;
 esac
 
-# 
+#
 # install the new server
-ln -sfn /export/doocs/server/llrfCtrl_server/bin/llrfctrl /export/doocs/server/llrfCtrl_server/llrfCtrl_server
+if [ -f /export/doocs/server/llrfCtrl_server/bin/llrfctrl ]; then
+  ln -sfn /export/doocs/server/llrfCtrl_server/bin/llrfctrl /export/doocs/server/llrfCtrl_server/llrfCtrl_server
+elif [ -f /export/doocs/server/llrfCtrl_server/bin/llrfctrl-server ]; then
+  ln -sfn /export/doocs/server/llrfCtrl_server/bin/llrfctrl-server /export/doocs/server/llrfCtrl_server/llrfCtrl_server
+else
+  echo "Cannot find executable from package."
+	exit 1
+fi
 
 #
 # generate and/or update configuration files. Server will be stopped, added to watchdog and started again inside this script
