added: detection of accelerator.

diff --git a/doocs-dism-server/postinst b/doocs-dism-server/postinst
--- a/doocs-dism-server/postinst
+++ b/doocs-dism-server/postinst
@@ -21,6 +21,18 @@ NODENAME=`uname -n`
 UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `
 
 #
+# ACCELERATOR
+#
+if [ ${NODENAME:0:6} == "xfelml" ] || [ ${NODENAME:0:9} == "xfelcpull" ];then
+  ACCELERATOR="XFEL"
+elif [ ${NODENAME:0:7} == "flashml" ] || [ ${NODENAME:0:10} == "flashcpull" ] || [ ${NODENAME:0:9} == "mskcpuacc" ];then
+  ACCELERATOR="FLASH"
+else
+  echo 2>&1 "Cannot determine accelerator"
+  exit 1
+fi
+
+#
 # RPC_LIBNO
 # 
 if [ -f /export/doocs/server/dism_server/RPC_LIBNO ] ; then
@@ -29,6 +41,20 @@ export RPC_LIBNO
 else
   echo 2>&1 "File: /export/doocs/server/dism_server/RPC_LIBNO is missing"
   exit 1
+fi
+
+## Note: The old config stuff has been removed. The server is written with the current style.
+
+if [ ! -f /export/doocs/server/dism_server/dism_server.conf  ] ; then
+   if [ -f /export/doocs/server/dism_server/dism_CONF.TEMPLATE ] ; then
+      cat /export/doocs/server/dism_server/dism_CONF.TEMPLATE | \
+       sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g"| \
+       sed -e "s/ACCELERATOR/$ACCELERATOR/g" > \
+       /export/doocs/server/dism_server/dism_server.conf
+      chown doocsadm.doocsadm /export/doocs/server/dism_server/dism_server.conf
+   else
+       echo "!!! no dism template !!! "
+   fi
 fi
 
 ###
