added: get the accelerator name.

diff --git a/doocs-mosyn100-server/postinst b/doocs-mosyn100-server/postinst
--- a/doocs-mosyn100-server/postinst
+++ b/doocs-mosyn100-server/postinst
@@ -23,6 +23,18 @@ NODENAME=`uname -n`
 UNODENAME=`uname -n | sed -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/" `
 
 #
+# ACCELERATOR
+#
+if [ ${NODENAME:0:6} == "xfelml" ] || [ ${NODENAME:0:9} == "xfelcpull" ];then
+  ACCELERATOR="XFEL"
+elif [ ${NODENAME:0:7} == "flashml" ] || [ ${NODENAME:0:10} == "flashcpull" ] || [ ${NODENAME:0:9} == "mskcpuacc" ];then
+  ACCELERATOR="FLASH"
+else
+  echo 2>&1 "Cannot determine accelerator"
+  exit 1
+fi
+
+#
 # RPC_LIBNO
 # 
 if [ -f /export/doocs/server/mosyn100_server/RPC_LIBNO ] ; then
@@ -38,7 +50,8 @@ fi
 if [ ! -f /export/doocs/server/mosyn100_server/mosyn100_server.conf  ] ; then
    if [ -f /export/doocs/server/mosyn100_server/mosyn100_CONF.TEMPLATE ] ; then
       cat /export/doocs/server/mosyn100_server/mosyn100_CONF.TEMPLATE | \
-       sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" > \
+       sed -e "s/NODENAME/$UNODENAME/g" | sed -e "s/nodename/$NODENAME/g" | \
+       sed -e "s/ACCELERATOR/$ACCELERATOR/g" > \
        /export/doocs/server/mosyn100_server/mosyn100_server.conf
       chown doocsadm.doocsadm /export/doocs/server/mosyn100_server/mosyn100_server.conf
    else
